Repository mainmatter/ember-simple-auth, pull requests merged in 2019-07, with the labels that each got.

#1886 session-stores/cookie: Convert private volatile properties to methods
  addon/session-stores/cookie.js
Labels: enhancement

#1885 oauth2-password-grant: Convert `tokenRefreshOffset` to a native getter
  addon/authenticators/oauth2-password-grant.js
  tests/unit/authenticators/oauth2-password-grant-test.js
Labels: enhancement

#1893 yarn: Deduplicate transitive dependencies
  yarn.lock
Labels: internal

#1894 Update Changelog and introduce lerna-changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: documentation

#1895 CI: Remove `v` prefix from version tag constraint
  .travis.yml
Labels: internal

#1900 Rename `_router` property to `_authRouter` to avoid conflicts
  addon/mixins/authenticated-route-mixin.js
  tests/unit/mixins/authenticated-route-mixin-test.js
Labels: enhancement

#1902 CI: Update npm API key
  .travis.yml
Labels: internal
