Repository mainmatter/ember-simple-auth, pull requests merged in 2019-11, with the labels that each got.

#1941 Update with async/await example
  README.md
Labels: documentation, enhancement

#2004 make ember-fetch a peer dependency
  package.json
  yarn.lock
Labels: breaking, dependencies

#2005 upgrade ember-cli-babel dependency to latest
  package.json
  yarn.lock
Labels: breaking, dependencies

#2020 fix configuration options use
  guides/upgrade-to-v3.md
Labels: documentation

#2032 Use `on` modifier rather in octane examples
  guides/octane-auth-torii-with-github.md
Labels: documentation

#2034 switch to github actions
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  .travis.yml
  package.json
  server/package.json
  yarn.lock
Labels: internal
