Repository mainmatter/ember-simple-auth, pull requests merged in 2023-03, with the labels that each got.

#2520 Update managing-current-user.md
  guides/managing-current-user.md
Labels: documentation

#2521 Fix the link to README.md.
  api/index.html
Labels: documentation

#2526 feat: remove deprecated Evented API usage from the public session service
  packages/ember-simple-auth/addon/services/session.js
  packages/ember-simple-auth/tests/unit/services/session-test.js
Labels: breaking

#2527 chore: prolong Torri authenticator deprecation period until v6
  packages/ember-simple-auth/addon/authenticators/torii.js
Labels: internal

#2525 chore: Drop node - set minimal node version to >=16
  .github/workflows/release.yml
  README.md
  package.json
  packages/ember-simple-auth/package.json
Labels: breaking

#2528 chore(deps): remove jsdom resolutions
  packages/classic-test-app/package.json
  packages/ember-simple-auth/package.json
  packages/test-app/package.json
Labels: dependencies
