Repository mainmatter/ember-simple-auth, pull requests merged in 2023-04, with the labels that each got.

#2537 chore(deps): remove ember-export-application-global
  packages/classic-test-app/package.json
  packages/ember-simple-auth/package.json
  packages/test-app/package.json
  yarn.lock
Labels: dependencies

#2542 Use Object.assign and drop Ember.assign
  packages/ember-simple-auth/addon/authenticators/devise.js
  packages/ember-simple-auth/addon/authenticators/oauth2-password-grant.js
  packages/ember-simple-auth/addon/authenticators/torii.js
  packages/ember-simple-auth/addon/internal-session.js
  packages/ember-simple-auth/addon/utils/assign.js
  packages/ember-simple-auth/tests/helpers/create-adaptive-store.js
  packages/ember-simple-auth/tests/helpers/start-app.js
  packages/ember-simple-auth/tests/unit/session-stores/adaptive-test.js
  packages/ember-simple-auth/tests/unit/session-stores/cookie-test.js
  packages/ember-simple-auth/tests/unit/utils/assign-test.js
Labels: breaking

#2545 chore: install @ember/string in packages directly
  packages/classic-test-app/package.json
  packages/ember-simple-auth/package.json
  packages/test-app/package.json
  yarn.lock
Labels: dependencies

#2546 chore(deps): bump ember-cookies to v1.0.0
  packages/ember-simple-auth/package.json
  yarn.lock
Labels: dependencies

#2548 refactor(deprecation): use findRecord instead of find
  packages/classic-test-app/app/routes/auth-error.js
  packages/classic-test-app/app/services/session-account.js
  packages/test-app/app/routes/auth-error.js
  packages/test-app/app/services/session-account.js
Labels: internal

#2544 feat(breaking): drop ember < v3.28 and IE11 support
  .github/workflows/ci.yml
  README.md
  packages/ember-simple-auth/addon/authenticators/torii.js
  packages/ember-simple-auth/config/ember-try.js
  packages/ember-simple-auth/package.json
Labels: breaking
