Repository mainmatter/ember-simple-auth, pull requests merged in 2024-12, with the labels that each got.

#2860 Action helper and modifier are deprecated in login-form.hbs
  packages/test-app/app/templates/components/login-form.hbs
Labels: internal

#2874 feat: Use native promises, remove RSVP
  package.json
  packages/ember-simple-auth/src/authenticators/base.js
  packages/ember-simple-auth/src/authenticators/devise.js
  packages/ember-simple-auth/src/authenticators/oauth2-implicit-grant.js
  packages/ember-simple-auth/src/authenticators/oauth2-password-grant.js
  packages/ember-simple-auth/src/authenticators/test.js
  packages/ember-simple-auth/src/authenticators/torii.js
  packages/ember-simple-auth/src/internal-session.js
  packages/ember-simple-auth/src/services/session.js
  packages/ember-simple-auth/src/session-stores/adaptive.js
  packages/ember-simple-auth/src/session-stores/base.js
  packages/ember-simple-auth/src/session-stores/cookie.js
  packages/ember-simple-auth/src/session-stores/ephemeral.js
  packages/ember-simple-auth/src/session-stores/local-storage.js
  packages/ember-simple-auth/src/session-stores/session-storage.js
  packages/ember-simple-auth/src/test-support/index.js
  packages/test-esa/tests/unit/authenticators/torii-test.js
  packages/test-esa/tests/unit/internal-session-test.js
  packages/test-esa/tests/unit/services/session-test.js
  packages/test-esa/tests/unit/session-stores/shared/storage-event-handler-behavior.js
Labels: breaking

#2875 Remove Evented mixin. Use native EventTarget.
  packages/ember-simple-auth/src/authenticators/base.js
  packages/ember-simple-auth/src/internal-session.js
  packages/ember-simple-auth/src/session-stores/adaptive.js
  packages/ember-simple-auth/src/session-stores/base.js
  packages/test-esa/tests/unit/authenticators/oauth2-password-grant-test.js
  packages/test-esa/tests/unit/internal-session-test.js
  packages/test-esa/tests/unit/session-stores/shared/cookie-store-behavior.js
  packages/test-esa/tests/unit/session-stores/shared/store-behavior.js
Labels: breaking

#2876 refactor(all): use on modifier. Action template helper dropped in 6.0
  packages/classic-test-app/app/components/login-form.js
  packages/classic-test-app/app/components/main-navigation.js
  packages/classic-test-app/app/templates/components/login-form.hbs
  packages/classic-test-app/app/templates/components/main-navigation.hbs
  packages/classic-test-app/lib/my-engine/addon/controllers/index.js
  packages/classic-test-app/lib/my-engine/addon/templates/index.hbs
  packages/test-app/app/components/login-form.js
  packages/test-app/app/templates/application.hbs
  packages/test-app/app/templates/components/login-form.hbs
  packages/test-app/lib/my-engine/addon/templates/protected.hbs
Labels: internal

#2878 refactor(ember-simple-auth): authenticators to use ES6 classes
  packages/ember-simple-auth/src/authenticators/devise.js
  packages/ember-simple-auth/src/authenticators/oauth2-implicit-grant.js
  packages/ember-simple-auth/src/authenticators/oauth2-password-grant.js
  packages/ember-simple-auth/src/authenticators/test.js
  packages/ember-simple-auth/src/authenticators/torii.js
  packages/test-esa/tests/unit/authenticators/devise-test.js
Labels: internal

#2880 refactor(ember-simple-auth): local-storage, session-storage, ephemeral to ES6 class.
  packages/ember-simple-auth/src/session-stores/ephemeral.js
  packages/ember-simple-auth/src/session-stores/local-storage.js
  packages/ember-simple-auth/src/session-stores/session-storage.js
  packages/test-esa/tests/unit/session-stores/ephemeral-test.js
  packages/test-esa/tests/unit/session-stores/local-storage-test.js
  packages/test-esa/tests/unit/session-stores/session-storage-test.js
  packages/test-esa/tests/unit/session-stores/shared/storage-event-handler-behavior.js
Labels: internal

#2881 refactor(ember-simple-auth): adaptive store to es6
  packages/ember-simple-auth/src/session-stores/adaptive.js
  packages/test-esa/tests/helpers/create-adaptive-store.js
  packages/test-esa/tests/unit/session-stores/adaptive-test.js
  packages/test-esa/tests/unit/session-stores/shared/cookie-store-behavior.js
Labels: internal

#2872 chore(typescript): ember-simple-auth initial setup
  eslint.config.mjs
  package.json
  packages/ember-simple-auth/.eslintignore
  packages/ember-simple-auth/babel.config.json
  packages/ember-simple-auth/package.json
  packages/ember-simple-auth/rollup.config.mjs
  packages/ember-simple-auth/src/utils/is-fastboot.ts
  packages/ember-simple-auth/tsconfig.json
  pnpm-lock.yaml
Labels: breaking

#2883 refactor(typescript): migrate BaseAuthenticator and OAuthPasswordGrant
  packages/ember-simple-auth/package.json
  packages/ember-simple-auth/src/authenticators/base.ts
  packages/ember-simple-auth/src/authenticators/devise.ts
  packages/ember-simple-auth/src/authenticators/oauth2-implicit-grant.ts
  packages/ember-simple-auth/src/authenticators/oauth2-password-grant.ts
  packages/ember-simple-auth/src/authenticators/test.ts
  packages/ember-simple-auth/src/authenticators/torii.js
  packages/test-esa/tests/unit/authenticators/test-test.js
  pnpm-lock.yaml
Labels: enhancement

#2884 refactor(typescript): migrate session-stores to typescript
  packages/ember-simple-auth/babel.config.json
  packages/ember-simple-auth/src/authenticators/base.ts
  packages/ember-simple-auth/src/session-stores/adaptive.ts
  packages/ember-simple-auth/src/session-stores/application.js
  packages/ember-simple-auth/src/session-stores/application.ts
  packages/ember-simple-auth/src/session-stores/base.ts
  packages/ember-simple-auth/src/session-stores/cookie.ts
  packages/ember-simple-auth/src/session-stores/ephemeral.ts
  packages/ember-simple-auth/src/session-stores/local-storage.ts
  packages/ember-simple-auth/src/session-stores/session-storage.ts
Labels: internal

#2885 feat(ember-simple-auth): Remove unused inject util
  packages/ember-simple-auth/src/test-support/index.ts
  packages/ember-simple-auth/src/utils/inject.js
  packages/test-esa/tests/unit/utils/assign-test.js
Labels: breaking

#2887 feat(ember-simple-auth): implement internal EventTarget
  packages/ember-simple-auth/package.json
  packages/ember-simple-auth/src/-internals/event-target.ts
  packages/ember-simple-auth/src/authenticators/base.ts
  packages/ember-simple-auth/src/internal-session.js
  packages/ember-simple-auth/src/session-stores/base.ts
  packages/ember-simple-auth/src/session-stores/local-storage.ts
  packages/ember-simple-auth/src/session-stores/session-storage.ts
  packages/test-app/package.json
  pnpm-lock.yaml
Labels: internal

#2889 chore(ember-simple-auth): depend on ember-cookies >=1.3.0
  packages/ember-simple-auth/package.json
  pnpm-lock.yaml
Labels: dependencies

#2890 chore(ember-simple-auth): specify addon exports
  packages/ember-simple-auth/package.json
  packages/ember-simple-auth/rollup.config.mjs
  packages/ember-simple-auth/src/services/session.ts
Labels: internal

#2891 fix(ember-simple-auth): parse expirationTime before setting it
  packages/ember-simple-auth/src/session-stores/cookie.ts
Labels: bug

#2892 chore(deps): specify ember-simple-auth as a link for test-apps
  guides/upgrade-to-v7.md
  packages/classic-test-app/app/authenticators/oauth2.js
  packages/classic-test-app/app/components/login-form.js
  packages/classic-test-app/app/controllers/application.js
  packages/classic-test-app/package.json
  packages/test-app/package.json
  pnpm-lock.yaml
Labels: documentation, internal

#2894 fix(deps): remove babel/eslint-parser from ESA dependencies
  packages/ember-simple-auth/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#2895 feat(ember-simple-auth): remove app re-exports
  README.md
  guides/upgrade-to-v7.md
  packages/ember-simple-auth/package.json
  packages/ember-simple-auth/rollup.config.mjs
  packages/test-esa/app/services/session.js
  packages/test-esa/app/session-stores/application.js
Labels: breaking

#2888 Typescript test app
  packages/classic-test-app/package.json
  packages/test-app/app/controllers/index.ts
  packages/test-app/app/services/session.js
  packages/test-app/app/services/session.ts
  packages/test-app/app/session-stores/application.js
  packages/test-app/babel.config.json
  packages/test-app/ember-cli-build.js
  packages/test-app/package.json
  packages/test-app/tsconfig.json
  packages/test-app/types/global.d.ts
  pnpm-lock.yaml
Labels: internal

#2893 doc: v7 release guide
  README.md
  guides/upgrade-to-v7.md
Labels: documentation

#2897 feat(test-apps): fix Ember 5.x deprecations. Support Ember 6.0 testing
  .github/workflows/ci.yml
  packages/classic-test-app/app/components/login-form.hbs
  packages/classic-test-app/app/components/main-navigation.hbs
  packages/classic-test-app/app/controllers/application.js
  packages/classic-test-app/app/templates/application.hbs
  packages/classic-test-app/app/templates/components/.gitkeep
  packages/test-app/app/components/login-form.hbs
  packages/test-app/app/components/main-navigation.hbs
  packages/test-app/app/templates/components/.gitkeep
  packages/test-esa/config/ember-try.js
Labels: internal

#2902 feat(ember-simple-auth): add generic type argument to session
  README.md
  packages/ember-simple-auth/src/services/session.ts
  packages/test-app/app/controllers/index.ts
  packages/test-app/app/services/session.ts
Labels: enhancement

#2905 feat(test-esa) fix missing test scenarios
  .github/workflows/ci.yml
  packages/test-esa/config/ember-try.js
Labels: internal

#2906 doc: support typescript doc generation
  packages/docs/jsdoc.json
  pnpm-lock.yaml
Labels: documentation
