Repository mainmatter/ember-simple-auth, pull requests merged in 2024-09, with the labels that each got.

#2812 chore(docs): move events to an internal session
  packages/ember-simple-auth/src/internal-session.js
  packages/ember-simple-auth/src/services/session.js
Labels: documentation

#2817 chore(release): make sure every package is private
  packages/classic-test-app/lib/my-engine/package.json
  packages/docs/package.json
  packages/test-app/lib/my-engine/package.json
Labels: internal

#2820 chore(release): fix release
  .github/workflows/publish.yml
Labels: internal

#2822 chore(deps): install eslint-config-prettier
  package.json
  pnpm-lock.yaml
Labels: internal

#2824 chore(deps): lock maintenance
  pnpm-lock.yaml
Labels: dependencies

#2834 Verified and updated links to ember-simple-auth.com/api/
  README.md
Labels: documentation
