Repository mainmatter/ember-simple-auth, pull requests merged in 2025-01, with the labels that each got.

#2909 fix(ember-simple-auth): setting non 'content' fields with #set on ObjectProxy is not reactive.
  packages/ember-simple-auth/src/services/session.ts
  packages/test-app/app/controllers/application.js
  packages/test-app/app/templates/application.hbs
  packages/test-app/tests/acceptance/authentication-test.js
Labels: bug

#2908 fix pnpm peer dependency warning
  packages/ember-simple-auth/package.json
  pnpm-lock.yaml
Labels: internal

#2920 chore(lint): remove .eslintignore files
  .eslintignore
  packages/classic-test-app/.eslintignore
  packages/test-app/.eslintignore
  packages/test-esa/.eslintignore
Labels: dependencies

#2919 fix(typescript): test-support types path
  packages/ember-simple-auth/package.json
  packages/test-app/app/app.ts
  packages/test-app/app/config/environment.d.ts
  packages/test-app/package.json
  packages/test-app/tests/acceptance/authentication-test.ts
  packages/test-app/tests/test-helper.ts
  pnpm-lock.yaml
Labels: bug

#2928 The authenticate method returns a Promise
  packages/ember-simple-auth/src/services/session.ts
Labels: bug
